tasks:
  - init: |
      pyenv virtualenv 3.8.13 pqsql
      echo "pqsql" > .python-version
      poetry install

  - command: |
        pyenv activate pqsql
        poetry install

vscode:
  extensions:
    - ms-python.python